### ISSUE TITLE
key must not contain '.'

### ISSUE THREAD

**Issue by henrikekblad** [BenLubar/nodebb-postgres-converter#13]
Hi!

Run into some problem when trying to convert my redis forum instance to mongodb. Any idea why this is happening?

```
[2019-12-22 12:36:52.568] [LOG]    Counting objects...
[2019-12-22 12:39:50.423] [LOG]    Attempting to copy 8983120 objects...
[2019-12-22 12:40:06.855] [LOG]      1% - 99966 objects copied (34 skipped)
[2019-12-22 12:40:22.732] [LOG]      2% - 199931 objects copied (69 skipped)
[2019-12-22 12:40:37.562] [LOG]      3% - 299905 objects copied (95 skipped)
[2019-12-22 12:40:53.303] [LOG]      4% - 399878 objects copied (122 skipped)
[2019-12-22 12:41:07.994] [LOG]      5% - 499859 objects copied (141 skipped)
[2019-12-22 12:41:22.526] [LOG]      6% - 599835 objects copied (165 skipped)
[2019-12-22 12:41:35.985] [LOG]      7% - 699824 objects copied (176 skipped)
[2019-12-22 12:41:52.316] [LOG]      8% - 799798 objects copied (202 skipped)
[2019-12-22 12:42:03.276] [LOG]     10% - 899779 objects copied (221 skipped)
[2019-12-22 12:42:14.087] [LOG]     11% - 999754 objects copied (246 skipped)
[2019-12-22 12:42:23.742] [LOG]     12% - 1099739 objects copied (261 skipped)
[2019-12-22 12:42:32.031] [LOG]     13% - 1199735 objects copied (265 skipped)
[2019-12-22 12:42:42.365] [LOG]     14% - 1299713 objects copied (287 skipped)
[2019-12-22 12:42:52.108] [LOG]     15% - 1399696 objects copied (304 skipped)
[2019-12-22 12:43:02.536] [LOG]     16% - 1499670 objects copied (330 skipped)
[2019-12-22 12:43:12.335] [LOG]     17% - 1599648 objects copied (352 skipped)
[2019-12-22 12:43:22.989] [LOG]     18% - 1699621 objects copied (379 skipped)
[2019-12-22 12:43:33.393] [LOG]     20% - 1799589 objects copied (411 skipped)
[2019-12-22 12:43:44.159] [LOG]     21% - 1899558 objects copied (442 skipped)
[2019-12-22 12:43:44.262] [LOG]    Copy objects: 411693.878ms
[2019-12-22 12:43:44.264] [LOG]    Full conversion: 411730.098ms
[2019-12-22 12:43:44.265] [ERROR]  Error: key henrik.karlsson@mydomain.org must not contain '.'
    at serializeInto (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/bson/lib/bson/parser/serializer.js:913:19)
    at serializeObject (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/bson/lib/bson/parser/serializer.js:727:17)
    at serializeObject (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/bson/lib/bson/parser/serializer.js:937:17)
    at BSON.serialize (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/bson/lib/bson/bson.js:63:28)
    at Query.toBin (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/mongodb-core/lib/connection/commands.js:140:25)
    at Pool.write (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/mongodb-core/lib/connection/pool.js:986:23)
    at executeWrite (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:73:10)
    at WireProtocol.insert (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:84:3)``

**Comment by henrikekblad** [comment]
Found dots in three redis objects with _key: "username:uid_old", "email:uid_old" and "email:confirmed". Not sure how important they are for a functional form?

**Comment by henrikekblad** [comment]
Fixed by #15
