### ISSUE TITLE
WiredTigerIndex::insert: key too large to index

### ISSUE THREAD

**Issue by henrikekblad** [BenLubar/nodebb-postgres-converter#14]
Ok, when skipping document containing "." keys (#13) I got a little further. But it fails trying to create the index due to the following error:

```
2019-12-22 15:39:41.965] [LOG]     99% - 8898386 objects copied (1614 skipped)
[2019-12-22 15:39:50.962] [LOG]    100% - 8981871 objects copied (1631 skipped)
[2019-12-22 15:39:50.962] [WARN]   There were 8983502 objects, but 8983481 were expected.
[2019-12-22 15:39:50.963] [LOG]    Copy objects: 1140751.534ms
[2019-12-22 15:41:23.041] [LOG]    Full conversion: 1232863.148ms
[2019-12-22 15:41:23.042] [ERROR]  MongoError: WiredTigerIndex::insert: key too large to index, failing  1206 { : "errors:404", : "/unreaddata:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAADIklEQVQ4T5XTa0iTURgH8P+7dxffbe82N2trrnRz87ZW1kwy7K5ZWEZ2kSiiQJOsrIigG/WhD..." }
    at Function.MongoError.create (/usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/mongodb-core/lib/error.js:31:11)
    at /usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/mongodb/lib/db.js:1096:80
    at /usr/lib/node_modules/@ben_lubar/nodebb-postgres-converter/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by henrikekblad** [comment]
Fixed by #15
